!About section commands
This command is a section command (also called special section). Common 
to all section commands is the fact that the section continues until a blank 
line or another section command is encountered.\n
The section commands are:\n
- $\\bug, \\deprecated, \\throw, \\internal, \\note, \\param, \\remark, \\sa, \\todo,
     \\warning$ }(Multiple commands are allowed yielding a bulleted list)}
- $\\author, \\brief, \\return, \\version$ }(Only intended to be used once per entity)}