
!About section commands
This command is a section command (also called "Special Sections"). Common 
to all section commands is the fact that the section continues until a blank 
line or another section command is encountered.\n
The section commands are:\n
- $\\bug, \\throw, \\internal, \\note, \\param, \\remark, \\sa, \\todo,
     \\warning \\since$ }(Multiple commands are allowed yielding a bulleted list)}
- $\\author \\version }(Multiple commands are are comma separated in output)}
- $\\brief, \\return, \\deprecated }(Only intended to be used once per entity)}
