!!About putting the documentation in separate files
This command is used for documenting an entity away from it's definition in the 
code. See SeparateDocs for some examples.\n
The commands for making separate documentation are:\n
$\\class, \\def, \\enum, (\\file), \\fn, \\namespace, \\struct, \\typedef, \\union 
\\var$
!Qualify with scope (class, namepace) if inside a scope like this:
\code
\enum SepDocClass::ClassEnum
\endcode
