!!! DoxyS manual

On these pages you will find the documentation for DoxyS itself. How to document 
code, reference manuals, example code with output and information on how to run 
the program. Also build/compile instructions are located here.

The Documenting pages decribe how to document your code using DoxyS. Also there 
is a quick example found in the "Example Code" section which is called HowToDocument.

The "Running DoxyS" section provides information on how to run the program, which 
basically just implies typing $doxys$ in the root of your code directory. This will 
create a default configuration file called $"DoxySfile"$, which is then used for 
generating the documentation. The config options are described in detail in "Config Options".

